[UPDATE] Update ci.env and ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,11 +30,11 @@ jobs:
         # wait-for-it sẽ đợi tối đa 60s cho cổng 8080 mở
         # Kích hoạt profile 'ci' để ứng dụng dùng H2 DB thay vì DB thật
         run: |
-          docker run -d -p 8080:8080 --name studio-app -e SPRING_PROFILES_ACTIVE=ci booking-studio
+          docker run -d -p 8080:8080 --name studio-app --env-file ci.env -e SPRING_PROFILES_ACTIVE=ci booking-studio
           wait-for-it localhost:8080 -t 60 --strict
-          echo "Port is open. Waiting 1 seconds for Spring Boot to stabilize..."
-          sleep 1
-          curl --fail http://localhost:8080/actuator/health
+          echo "Port is open. Waiting 5 seconds for Spring Boot to stabilize..."
+          sleep 5
+          curl --fail http://localhost:8080/actuator/health || (echo "Health check failed, checking logs..." && exit 1)
 
       - name: Show Docker Logs on Failure
         if: failure()
